# Generated by Django 5.2.9 on 2026-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, default='records/default.png', null=True, upload_to='records/'),
        ),
    ]
